### ISSUE TITLE
swipeback与'com.android.support:design:23.0.1'有冲突，导致APP闪退。

### ISSUE THREAD

**Issue by jaffwu** [bluzwong/swipeback#1]
项目是使用android studio应用模板“Tabbed Activity”创建的。在FloatingActionButton注册事件调用startSwipeActivity，当事件触发时，APP闪退。

Log信息：
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime: FATAL EXCEPTION: Thread-9258
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:5453)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1031)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.invalidateChild(ViewGroup.java:4206)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.invalidate(View.java:10452)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.drawAnimation(View.java:13442)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.draw(View.java:13551)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1074)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.draw(View.java:13809)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.draw(View.java:13947)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.widget.FrameLayout.draw(FrameLayout.java:467)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.draw(View.java:13814)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.draw(View.java:13947)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.draw(View.java:13814)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.support.v4.widget.SlidingPaneLayout.drawChild(SlidingPaneLayout.java:1013)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.draw(View.java:13947)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.support.v4.widget.SlidingPaneLayout.draw(SlidingPaneLayout.java:1155)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.draw(View.java:13814)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.draw(View.java:13809)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.draw(View.java:13809)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.drawChild(ViewGroup.java:3050)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2912)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.draw(View.java:13947)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.widget.FrameLayout.draw(FrameLayout.java:467)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2247)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.buildDrawingCache(View.java:13167)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.getDrawingCache(View.java:12944)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at android.view.View.getDrawingCache(View.java:12909)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at com.github.bluzwong.swipeback.SwipeBackActivityHelper$3.run(SwipeBackActivityHelper.java:273)
10-14 16:36:45.833 19134-19277/wu.ian.myapplication E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:838)

**Comment by bluzwong** [comment]
可以提供一下闪退的log信息吗？

**Comment by bluzwong** [comment]
感谢您的反馈,请使用如下版本尝试,谢谢!
compile 'com.github.bluzwong:swipeback:0.1.3@aar'
